# Generated by Django 5.1.7 on 2025-08-22 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('ppid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('mem_rss', models.BigIntegerField(blank=True, null=True)),
                ('mem_percent', models.FloatField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='monitoring.snapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'pid'], name='monitoring__snapsho_e629fb_idx'), models.Index(fields=['snapshot', 'ppid'], name='monitoring__snapsho_8c86fe_idx')],
            },
        ),
    ]
